create table if not exists public.admin_audit_events (
  id bigint generated by default as identity primary key,
  action text not null,
  actor text not null,
  request_path text not null,
  ip_address text null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists admin_audit_events_created_at_idx
on public.admin_audit_events(created_at desc);

create index if not exists admin_audit_events_action_idx
on public.admin_audit_events(action);
